### ISSUE TITLE
White label issue is not solved for this SDK

### ISSUE THREAD

**Issue by negapo** [dymosoftware/DCD-SDK-Sample#24] opened 2021-03-18 17:40 UTC
Hi, the update done to DCD and DLS8 solved the white label issue when printing thru the Dymo UI on both apps and also when using the Interop.Dymo and the Dymo.Label.Framework SDK but it did not solve the issue when using the DymoSDK, you can test it using the sample project in C#
Do we need to wait for another update? Thanks

**Comment by ph01n1x** [comment] 2021-03-24 15:43
Is there any update on this? DCD solved the white label issue already while the SDK still prints blank.

**Comment by negapo** [comment] 2021-03-24 20:36
It seems no one cares unfortunately.

**Comment by jakobcichon** [comment] 2021-03-24 21:05
I see walkaround here: https://www.dymo.com/en-US/software-fix

**Comment by ph01n1x** [comment] 2021-03-24 21:17
Yes that is temporary solution by removing a security update. But that's not the long term solution. And DYMO has already posted new version of their DC software that resolves this issue so regular Windows update can continue. But clearly DYMO has been ignoring the SDK side. Our customer is telling us that DYMO support claims that DYMO has fixed this issue. But yet we cannot do anything about our software because in reality DYMO hasn't fixed the issue because they have not fixed SDK.

**Comment by dymosoftware** [comment] 2021-03-24 23:15
Hey guys, we were focused on a fix for DYMO Connect and DYMO Label software the last days, we are about to start to work on a fix for SDK, hopefully next week we will get a beta/preview version that you might be able to test and confirm. We will keep you posted here and our channels.

**Comment by dymosoftware** [comment] 2021-03-25 19:08
We just published a preview fix, please update nuget package to version _1.3.2.14-alpha_ and confirm issue is fixed for you guys.
`Install-Package DYMO.Connect.SDK -Version 1.3.2.124-alpha`

**Comment by ph01n1x** [comment] 2021-03-25 19:40
Did a quick test here and it is still printing blank for me. The DC software prints the same label correctly.

**Comment by dymosoftware** [comment] 2021-03-25 19:57
> Did a quick test here and it is still printing blank for me. The DC software prints the same label correctly.
@ph01n1x please provide following information:

- > Label type and inlcude XML if possible
- > DYMO printer
- > Windows OS version

**Comment by ph01n1x** [comment] 2021-03-25 20:13
[DYMO.zip](https://github.com/dymosoftware/DCD-SDK-Sample/files/6207575/DYMO.zip)

Attached the DYMO label trying to print. Tested on DYMO LabelWriter 450.
Windows 10 Pro 20H2 19042.868

**Comment by ph01n1x** [comment] 2021-03-25 20:32
Okay update. Re-tested against Windows 10 Pro 20H2 19042.870 and it prints correctly. DC software prints the same label correctly on both 19042.868 and 19042.870. But SDK, for me at least, only prints on 19042.870 and is blank on 19042.868.

That suggests to me that for the SDK to work properly, the out of band KB5001649 released on 2021/03/18 is required.

**Comment by dymosoftware** [comment] 2021-03-26 16:01
@ph01n1x as workaround you may install [VC++ 2015-2019](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) on the machine where Windows 19042.868 is running to check if issue is fixed. [KB5001649 ](https://support.microsoft.com/en-us/topic/march-18-2021-kb5001649-os-builds-19041-870-and-19042-870-out-of-band-ebbe0617-3a63-467a-aaaa-2a4c68a6de33) (OS Builds 19041.870 and 19042.870) has a fix for printing graphical content with that fix even previous SDK versions should work fine.

**Comment by calgary123** [comment] 2021-03-29 15:51
@dymosoftware  -   is there going to be an actual fix for the SDK?  What is the schedule?
I can confirm that our previously working software still prints blank labels with the alpha release described here.

**Comment by dymosoftware** [comment] 2021-03-29 16:09
@calgary123 could you try to install  [VC++ 2015-2019](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) and check if the problem is fixed with alpha version.

**Comment by jotunskij** [comment] 2021-03-29 16:09
It seems as if you have mislabeled the actual DLLs in the new release, which makes the new alpha compare incorrectly with the old one. This causes MSI installer packages to not overwrite the DLLs upon installation. See screenshot below.

![bild](https://user-images.githubusercontent.com/1684523/112866165-c4cc3980-90b9-11eb-80a4-e85ecfd313be.png)

**Comment by dymosoftware** [comment] 2021-03-30 09:53
> It seems as if you have mislabeled the actual DLLs in the new release, which makes the new alpha compare incorrectly with the old one. This causes MSI installer packages to not overwrite the DLLs upon installation. See screenshot below.
> 
> Let me know if you'd rather I open a new issue for this!
> 
> ![bild](https://user-images.githubusercontent.com/1684523/112866165-c4cc3980-90b9-11eb-80a4-e85ecfd313be.png)

@jotunskij  [1.3.2.130-alpha](https://www.nuget.org/packages/DYMO.Connect.SDK/1.3.2.130-alpha) has a version patch labeling DYMO DLLs with correct version.

**Comment by jotunskij** [comment] 2021-03-30 11:57
Thanks @dymosoftware!

**Comment by jotunskij** [comment] 2021-03-30 15:38
The DymoSDK.dll file is still not being overwritten. This is probably due to it having the same file version in both releases. The other files have the same file version as product version set, which is the correct way to version DLLs as far as I know. Could you release a version with the file version fixed for DymoSDK.dll?

![bild](https://user-images.githubusercontent.com/1684523/113016366-b2680380-917e-11eb-9e0f-827e64e1119e.png)

**Comment by dymosoftware** [comment] 2021-03-30 23:17
> The DymoSDK.dll file is still not being overwritten. This is probably due to it having the same file version in both releases. The other files have the same file version as product version set, which is the correct way to version DLLs as far as I know. Could you release a version with the file version fixed for DymoSDK.dll?
> 
> ![bild](https://user-images.githubusercontent.com/1684523/113016366-b2680380-917e-11eb-9e0f-827e64e1119e.png)

Did you clean(delete bin folder) and rebuild your project? I tried on sample project updating to alpha version and DymoSDK.dll is latest version 1.3.2.130

![image](https://user-images.githubusercontent.com/57638744/113068601-9703f500-918c-11eb-9dea-d8419ab236c8.png)

**Comment by jotunskij** [comment] 2021-03-31 07:48
@dymosoftware The build overwrites the file correctly, but when I build my msi (a visual studio setup project), the dll does not get bundled correctly, since the file version is the same in both the 1.3.2.x and 1.3.1.x release.

**Comment by calgary123** [comment] 2021-04-05 16:06
@dymosoftware
I have updated the visual c++ distributable.
I have also updated via nuget to your latest alpha version v1.3.2.130-alpha

The printer just spits out a blank label at high speed.
The same labels prints (at a slower speed) the Connect software.

Any suggestions?

**Comment by arek159** [comment] 2021-04-05 20:24
Hi, in my case, i've updated to alpha version 1.3.2.130 and got an error:
`Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Nie można odnaleźć określonego pliku.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at DYMO.LabelAPI.Windows.PrinterDiscovery.WindowsDeviceDiscoveryAgent.Start()\r\n   at DYMO.LabelAPI.PrinterFactory.Initialize()\r\n   at DYMO.LabelAPI.PrinterFactory..ctor()\r\n   at DYMO.LabelAPI.PrinterFactory.get_Instance()\r\n   at DymoSDK.Implementations.DymoPrinter.get__printFactInstance()\r\n   at DymoSDK.Implementations.DymoPrinter.PrintLabel(DymoLabel label, String printerName, Int32 copies, Boolean collate, Boolean mirror, Int32 rollSelected, Boolean chainMarks, Boolean barcodeGraphsQuality)\r\n   at xxx","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147024894,"Source":"DYMO.LabelAPI.PlatformSpecific","WatsonBuckets":null,"FileNotFound_FileName":"System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","FileNotFound_FusionLog":""`

code usage:
`
DymoLabel.LoadLabelFromFilePath(pathToFile);

DymoPrinter.Instance.PrintLabel(DymoLabel, printerName, count);
`

file exists in output folder
![image](https://user-images.githubusercontent.com/7459644/113622530-6bd24780-965d-11eb-82e0-7af481350181.png)

**Comment by dymosoftware** [comment] 2021-04-09 13:27
> @dymosoftware The build overwrites the file correctly, but when I build my msi (a visual studio setup project), the dll does not get bundled correctly, since the file version is the same in both the 1.3.2.x and 1.3.1.x release.

Could you verify if 1.3.2.134-alpha fix this issue?

**Comment by jotunskij** [comment] 2021-04-09 16:02
@dymosoftware Yes! The DLLs all seem to be correctly installed now, and I can print labels as normal again. Huge thanks!
I've built a version of our software that one of our clients will test in the coming days. I'll let you know if they find anything.

**Comment by arek159** [comment] 2021-04-09 19:16
for me 1.3.2.134-alpha still prints blank labels

**Comment by jotunskij** [comment] 2021-04-09 19:17
@arek159 Did you update the Dymo Connect software to the latest version?

**Comment by dymosoftware** [comment] 2021-04-09 19:24
Have you updated Windows OS to version

> @dymosoftware
> I have updated the visual c++ distributable.
> I have also updated via nuget to your latest alpha version v1.3.2.130-alpha
> 
> The printer just spits out a blank label at high speed.
> The same labels prints (at a slower speed) the Connect software.
> 
> Any suggestions?

@arek159 Update DYMO Connect to latest version, if that doesn't work then upgrade Windows version to [KB5001649 ](https://support.microsoft.com/en-us/topic/march-18-2021-kb5001649-os-builds-19041-870-and-19042-870-out-of-band-ebbe0617-3a63-467a-aaaa-2a4c68a6de33).

**Comment by arek159** [comment] 2021-04-13 18:59
I have installed KB5001649 and it's been working, thanks :)

**Comment by alex-fitplans** [comment] 2021-04-14 16:06
Same thing here, I made it work with the updated package. Strangely though, when packaging my app in a zip and sending it over the internet, it would not work neither on the target machine.
It works fine when I zip/unzip on my machine, and if I zip, send it, download it on my machine, and unzip, I would get the issues.

To fix it, I had to manually copy the following files from the Program Files/Dymo to my app directory and overwrite the existing files:
* PrintingSupportLibrary.dll and _x64.dll (otherwise the app wouldn't even detect the printer)
* DymoPrinting.dll and _x64.dll (otherwise it would throw a TypeInitializationException when printing)

Not sure those issues are related to the alpha version though, just throwing that out there in case anyone faces the same issue.

Also, subscribing to the ticket to upgrade to the latest stable once the official fix is out. Thanks !

**Comment by JLOrdaz** [comment] 2021-04-16 16:53
I follow all step, working a PC and another not. I get this error:
![image](https://user-images.githubusercontent.com/4049041/115057936-a5535000-9eb2-11eb-9b6d-cf4a76e91a54.png)

**Comment by alex-fitplans** [comment] 2021-04-16 18:10
@JLOrdaz Try the steps I mentioned in my previous comment. It's a workaround but it did the trick for me

**Comment by calgary123** [comment] 2021-04-19 22:24
I did get it working.
The latest SDK and the latest Visual C++ distributable did the trick. My mistake was first updating just the 64 bit Visual C++ distributable. But after updating both the 32 and 64 bit versions on my computer I can print again.
Hope this helps.

**Comment by JLOrdaz** [comment] 2021-05-07 11:00
Today i download last sdk y i has installed Visual C++ distributable and I can print again. Its Working again. Thanks

**Closed** 2021-11-30 14:28 UTC
